#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InteractableOutwardDoor

#include "Basic.hpp"

#include "BP_InteractableOutwardDoor_classes.hpp"
#include "BP_InteractableOutwardDoor_parameters.hpp"


namespace SDK
{

// Function BP_InteractableOutwardDoor.BP_InteractableOutwardDoor_C.UpdateDoor
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  OpenProgress                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InteractableOutwardDoor_C::UpdateDoor(double OpenProgress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableOutwardDoor_C", "UpdateDoor");

	Params::BP_InteractableOutwardDoor_C_UpdateDoor Parms{};

	Parms.OpenProgress = OpenProgress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractableOutwardDoor.BP_InteractableOutwardDoor_C.StartOpeningFX
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_InteractableOutwardDoor_C::StartOpeningFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableOutwardDoor_C", "StartOpeningFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractableOutwardDoor.BP_InteractableOutwardDoor_C.StartClosingFX
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_InteractableOutwardDoor_C::StartClosingFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableOutwardDoor_C", "StartClosingFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractableOutwardDoor.BP_InteractableOutwardDoor_C.GetDoorMeshes
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UStaticMeshComponent*>*    Meshes                                                 (Parm, OutParm, ContainsInstancedReference)

void ABP_InteractableOutwardDoor_C::GetDoorMeshes(TArray<class UStaticMeshComponent*>* Meshes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableOutwardDoor_C", "GetDoorMeshes");

	Params::BP_InteractableOutwardDoor_C_GetDoorMeshes Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Meshes != nullptr)
		*Meshes = std::move(Parms.Meshes);
}


// Function BP_InteractableOutwardDoor.BP_InteractableOutwardDoor_C.ExecuteUbergraph_BP_InteractableOutwardDoor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InteractableOutwardDoor_C::ExecuteUbergraph_BP_InteractableOutwardDoor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableOutwardDoor_C", "ExecuteUbergraph_BP_InteractableOutwardDoor");

	Params::BP_InteractableOutwardDoor_C_ExecuteUbergraph_BP_InteractableOutwardDoor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractableOutwardDoor.BP_InteractableOutwardDoor_C.EndClosingFX
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_InteractableOutwardDoor_C::EndClosingFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableOutwardDoor_C", "EndClosingFX");

	UObject::ProcessEvent(Func, nullptr);
}

}

