#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LocalPlayerVoice

#include "Basic.hpp"

#include "BP_LocalPlayerVoice_classes.hpp"
#include "BP_LocalPlayerVoice_parameters.hpp"


namespace SDK
{

// Function BP_LocalPlayerVoice.BP_LocalPlayerVoice_C.ExecuteUbergraph_BP_LocalPlayerVoice
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LocalPlayerVoice_C::ExecuteUbergraph_BP_LocalPlayerVoice(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LocalPlayerVoice_C", "ExecuteUbergraph_BP_LocalPlayerVoice");

	Params::BP_LocalPlayerVoice_C_ExecuteUbergraph_BP_LocalPlayerVoice Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LocalPlayerVoice.BP_LocalPlayerVoice_C.LocalAudioEnvelopeValueChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const float                             EnvelopeValue                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LocalPlayerVoice_C::LocalAudioEnvelopeValueChanged(const float EnvelopeValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LocalPlayerVoice_C", "LocalAudioEnvelopeValueChanged");

	Params::BP_LocalPlayerVoice_C_LocalAudioEnvelopeValueChanged Parms{};

	Parms.EnvelopeValue = EnvelopeValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LocalPlayerVoice.BP_LocalPlayerVoice_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_LocalPlayerVoice_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LocalPlayerVoice_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LocalPlayerVoice.BP_LocalPlayerVoice_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LocalPlayerVoice_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LocalPlayerVoice_C", "ReceiveTick");

	Params::BP_LocalPlayerVoice_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

