#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupHelmetPress

#include "Basic.hpp"

#include "BP_PickupItem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PickupHelmetPress.BP_PickupHelmetPress_C
// 0x0000 (0x02E0 - 0x02E0)
class ABP_PickupHelmetPress_C final : public ABP_PickupItem_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PickupHelmetPress_C">();
	}
	static class ABP_PickupHelmetPress_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupHelmetPress_C>();
	}
};
static_assert(alignof(ABP_PickupHelmetPress_C) == 0x000008, "Wrong alignment on ABP_PickupHelmetPress_C");
static_assert(sizeof(ABP_PickupHelmetPress_C) == 0x0002E0, "Wrong size on ABP_PickupHelmetPress_C");

}

