#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StringTrap

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_StringTrap.BP_StringTrap_C.BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature) == 0x000020, "Wrong size on BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_StringTrap_C_BndEvt__StringTrap_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.ExecuteUbergraph_BP_StringTrap
// 0x0528 (0x0528 - 0x0000)
struct BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCloseToPlayers_CloseToPlayers;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_UPPlayerCharacter_C*                K2Node_Event_Player;                               // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0010(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0048(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0060(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x007B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x007D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x007E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x007F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_82[0x6];                                       // 0x0082(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A5[0x3];                                       // 0x00A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x00A8(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsTriggerActor_Result;                    // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_191[0x7];                                      // 0x0191(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_KillableCharacter_C*                CallFunc_IsTriggerActor_Character;                 // 0x0198(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_1;  // 0x01A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x01A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_1;       // 0x01B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BC[0x4];                                      // 0x01BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Killable_C>       K2Node_Event_HarmedActor;                          // 0x01C0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsTriggerActor_Result_1;                  // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D1[0x7];                                      // 0x01D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_KillableCharacter_C*                CallFunc_IsTriggerActor_Character_1;               // 0x01D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_3;                // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E2[0x6];                                      // 0x01E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Killable_C>       K2Node_Event_HarmedActor_1;                        // 0x01E8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_Killable_C>       K2Node_Event_KilledActor;                          // 0x01F8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_Killable_C>       K2Node_Event_KilledActor_1;                        // 0x0208(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_219[0x7];                                      // 0x0219(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_2;    // 0x0220(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_2;               // 0x0239(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_4;                 // 0x023A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23B[0x1];                                      // 0x023B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x023C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24C[0x4];                                      // 0x024C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0250(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_4;                // 0x0259(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_5;                 // 0x025A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25B[0x5];                                      // 0x025B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0260(0x0010)(ConstParm, ReferenceParm)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0270(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0358(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_359[0x7];                                      // 0x0359(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0360(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0448(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0449(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44A[0x2];                                      // 0x044A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x044C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0450(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_454[0x4];                                      // 0x0454(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0458(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0470(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0488(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x04A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x04B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x04C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x04C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x04D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x04D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x04E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x04E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x04E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EC[0x4];                                      // 0x04EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x04F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0508(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_K2_SetTimerDelegate_Time_ImplicitCast;    // 0x0520(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap) == 0x000008, "Wrong alignment on BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap");
static_assert(sizeof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap) == 0x000528, "Wrong size on BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, EntryPoint) == 0x000000, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsCloseToPlayers_CloseToPlayers) == 0x000004, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsCloseToPlayers_CloseToPlayers' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_Event_Player) == 0x000008, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_Event_Player' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000010, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000028, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsValid_ReturnValue) == 0x000029, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x000030, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_Add_VectorVector_ReturnValue) == 0x000048, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000060, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_HasAuthority_ReturnValue) == 0x000078, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_Not_PreBool_ReturnValue) == 0x000079, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_HasAuthority_ReturnValue_1) == 0x00007A, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BooleanAND_ReturnValue) == 0x00007B, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_Not_PreBool_ReturnValue_1) == 0x00007C, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsValid_ReturnValue_1) == 0x00007D, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BooleanAND_ReturnValue_1) == 0x00007E, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_Not_PreBool_ReturnValue_2) == 0x00007F, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_Not_PreBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BooleanAND_ReturnValue_2) == 0x000080, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BooleanAND_ReturnValue_3) == 0x000081, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000088, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_OtherActor) == 0x000090, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_OtherComp) == 0x000098, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x0000A0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_bFromSweep) == 0x0000A4, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_SweepResult) == 0x0000A8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsTriggerActor_Result) == 0x000190, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsTriggerActor_Result' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsTriggerActor_Character) == 0x000198, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsTriggerActor_Character' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_OverlappedComponent_1) == 0x0001A0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_OtherActor_1) == 0x0001A8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_OtherComp_1) == 0x0001B0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_ComponentBoundEvent_OtherBodyIndex_1) == 0x0001B8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_ComponentBoundEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_Event_HarmedActor) == 0x0001C0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_Event_HarmedActor' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsTriggerActor_Result_1) == 0x0001D0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsTriggerActor_Result_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsTriggerActor_Character_1) == 0x0001D8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsTriggerActor_Character_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsValid_ReturnValue_2) == 0x0001E0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_Not_PreBool_ReturnValue_3) == 0x0001E1, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_Not_PreBool_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_Event_HarmedActor_1) == 0x0001E8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_Event_HarmedActor_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_Event_KilledActor) == 0x0001F8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_Event_KilledActor' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_Event_KilledActor_1) == 0x000208, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_Event_KilledActor_1' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsVisible_ReturnValue) == 0x000218, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_K2_GetComponentLocation_ReturnValue_2) == 0x000220, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_K2_GetComponentLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsValid_ReturnValue_3) == 0x000238, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_HasAuthority_ReturnValue_2) == 0x000239, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_HasAuthority_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BooleanAND_ReturnValue_4) == 0x00023A, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BooleanAND_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, K2Node_CreateDelegate_OutputDelegate) == 0x00023C, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000250, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_IsValid_ReturnValue_4) == 0x000258, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_Not_PreBool_ReturnValue_4) == 0x000259, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_Not_PreBool_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BooleanAND_ReturnValue_5) == 0x00025A, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BooleanAND_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, Temp_object_Variable) == 0x000260, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_LineTraceSingle_OutHit) == 0x000270, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_LineTraceSingle_ReturnValue) == 0x000358, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000360, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_bBlockingHit) == 0x000448, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_bInitialOverlap) == 0x000449, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_Time) == 0x00044C, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_Distance) == 0x000450, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_Location) == 0x000458, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_ImpactPoint) == 0x000470, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_Normal) == 0x000488, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_ImpactNormal) == 0x0004A0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_PhysMat) == 0x0004B8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_HitActor) == 0x0004C0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_HitComponent) == 0x0004C8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_HitBoneName) == 0x0004D0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_BoneName) == 0x0004D8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_HitItem) == 0x0004E0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_ElementIndex) == 0x0004E4, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_FaceIndex) == 0x0004E8, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_TraceStart) == 0x0004F0, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_BreakHitResult_TraceEnd) == 0x000508, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap, CallFunc_K2_SetTimerDelegate_Time_ImplicitCast) == 0x000520, "Member 'BP_StringTrap_C_ExecuteUbergraph_BP_StringTrap::CallFunc_K2_SetTimerDelegate_Time_ImplicitCast' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.GetInteractDistance
// 0x0018 (0x0018 - 0x0000)
struct BP_StringTrap_C_GetInteractDistance final
{
public:
	double                                        Distance;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_UPPlayerCharacter_C*                K2Node_DynamicCast_AsBP_UPPlayer_Character;        // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_GetInteractDistance) == 0x000008, "Wrong alignment on BP_StringTrap_C_GetInteractDistance");
static_assert(sizeof(BP_StringTrap_C_GetInteractDistance) == 0x000018, "Wrong size on BP_StringTrap_C_GetInteractDistance");
static_assert(offsetof(BP_StringTrap_C_GetInteractDistance, Distance) == 0x000000, "Member 'BP_StringTrap_C_GetInteractDistance::Distance' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_GetInteractDistance, K2Node_DynamicCast_AsBP_UPPlayer_Character) == 0x000008, "Member 'BP_StringTrap_C_GetInteractDistance::K2Node_DynamicCast_AsBP_UPPlayer_Character' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_GetInteractDistance, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'BP_StringTrap_C_GetInteractDistance::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_GetInteractDistance, CallFunc_IsValid_ReturnValue) == 0x000011, "Member 'BP_StringTrap_C_GetInteractDistance::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.GetInteractDuration
// 0x0008 (0x0008 - 0x0000)
struct BP_StringTrap_C_GetInteractDuration final
{
public:
	double                                        Duration;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_GetInteractDuration) == 0x000008, "Wrong alignment on BP_StringTrap_C_GetInteractDuration");
static_assert(sizeof(BP_StringTrap_C_GetInteractDuration) == 0x000008, "Wrong size on BP_StringTrap_C_GetInteractDuration");
static_assert(offsetof(BP_StringTrap_C_GetInteractDuration, Duration) == 0x000000, "Member 'BP_StringTrap_C_GetInteractDuration::Duration' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.GetInteractNoise
// 0x0010 (0x0010 - 0x0000)
struct BP_StringTrap_C_GetInteractNoise final
{
public:
	bool                                          NoiseOnInteract;                                   // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        NoiseRange;                                        // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_GetInteractNoise) == 0x000008, "Wrong alignment on BP_StringTrap_C_GetInteractNoise");
static_assert(sizeof(BP_StringTrap_C_GetInteractNoise) == 0x000010, "Wrong size on BP_StringTrap_C_GetInteractNoise");
static_assert(offsetof(BP_StringTrap_C_GetInteractNoise, NoiseOnInteract) == 0x000000, "Member 'BP_StringTrap_C_GetInteractNoise::NoiseOnInteract' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_GetInteractNoise, NoiseRange) == 0x000008, "Member 'BP_StringTrap_C_GetInteractNoise::NoiseRange' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.GetInteractText
// 0x0018 (0x0018 - 0x0000)
struct BP_StringTrap_C_GetInteractText final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(Parm, OutParm)
};
static_assert(alignof(BP_StringTrap_C_GetInteractText) == 0x000008, "Wrong alignment on BP_StringTrap_C_GetInteractText");
static_assert(sizeof(BP_StringTrap_C_GetInteractText) == 0x000018, "Wrong size on BP_StringTrap_C_GetInteractText");
static_assert(offsetof(BP_StringTrap_C_GetInteractText, Text) == 0x000000, "Member 'BP_StringTrap_C_GetInteractText::Text' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.HasHarmed (All)
// 0x0010 (0x0010 - 0x0000)
struct BP_StringTrap_C_HasHarmed__All_ final
{
public:
	TScriptInterface<class IBPI_Killable_C>       HarmedActor;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_HasHarmed__All_) == 0x000008, "Wrong alignment on BP_StringTrap_C_HasHarmed__All_");
static_assert(sizeof(BP_StringTrap_C_HasHarmed__All_) == 0x000010, "Wrong size on BP_StringTrap_C_HasHarmed__All_");
static_assert(offsetof(BP_StringTrap_C_HasHarmed__All_, HarmedActor) == 0x000000, "Member 'BP_StringTrap_C_HasHarmed__All_::HarmedActor' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.HasHarmed (Server)
// 0x0010 (0x0010 - 0x0000)
struct BP_StringTrap_C_HasHarmed__Server_ final
{
public:
	TScriptInterface<class IBPI_Killable_C>       HarmedActor;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_HasHarmed__Server_) == 0x000008, "Wrong alignment on BP_StringTrap_C_HasHarmed__Server_");
static_assert(sizeof(BP_StringTrap_C_HasHarmed__Server_) == 0x000010, "Wrong size on BP_StringTrap_C_HasHarmed__Server_");
static_assert(offsetof(BP_StringTrap_C_HasHarmed__Server_, HarmedActor) == 0x000000, "Member 'BP_StringTrap_C_HasHarmed__Server_::HarmedActor' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.HasKilled (All)
// 0x0010 (0x0010 - 0x0000)
struct BP_StringTrap_C_HasKilled__All_ final
{
public:
	TScriptInterface<class IBPI_Killable_C>       KilledActor;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_HasKilled__All_) == 0x000008, "Wrong alignment on BP_StringTrap_C_HasKilled__All_");
static_assert(sizeof(BP_StringTrap_C_HasKilled__All_) == 0x000010, "Wrong size on BP_StringTrap_C_HasKilled__All_");
static_assert(offsetof(BP_StringTrap_C_HasKilled__All_, KilledActor) == 0x000000, "Member 'BP_StringTrap_C_HasKilled__All_::KilledActor' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.HasKilled (Server)
// 0x0010 (0x0010 - 0x0000)
struct BP_StringTrap_C_HasKilled__Server_ final
{
public:
	TScriptInterface<class IBPI_Killable_C>       KilledActor;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_HasKilled__Server_) == 0x000008, "Wrong alignment on BP_StringTrap_C_HasKilled__Server_");
static_assert(sizeof(BP_StringTrap_C_HasKilled__Server_) == 0x000010, "Wrong size on BP_StringTrap_C_HasKilled__Server_");
static_assert(offsetof(BP_StringTrap_C_HasKilled__Server_, KilledActor) == 0x000000, "Member 'BP_StringTrap_C_HasKilled__Server_::KilledActor' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.Interact
// 0x0008 (0x0008 - 0x0000)
struct BP_StringTrap_C_Interact final
{
public:
	class ABP_UPPlayerCharacter_C*                Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_Interact) == 0x000008, "Wrong alignment on BP_StringTrap_C_Interact");
static_assert(sizeof(BP_StringTrap_C_Interact) == 0x000008, "Wrong size on BP_StringTrap_C_Interact");
static_assert(offsetof(BP_StringTrap_C_Interact, Player) == 0x000000, "Member 'BP_StringTrap_C_Interact::Player' has a wrong offset!");

// Function BP_StringTrap.BP_StringTrap_C.IsTriggerActor
// 0x0028 (0x0028 - 0x0000)
struct BP_StringTrap_C_IsTriggerActor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_KillableCharacter_C*                Character;                                         // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_KillableCharacter_C*                K2Node_DynamicCast_AsBP_Killable_Character;        // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetAffinity_Affinity;                     // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StringTrap_C_IsTriggerActor) == 0x000008, "Wrong alignment on BP_StringTrap_C_IsTriggerActor");
static_assert(sizeof(BP_StringTrap_C_IsTriggerActor) == 0x000028, "Wrong size on BP_StringTrap_C_IsTriggerActor");
static_assert(offsetof(BP_StringTrap_C_IsTriggerActor, Actor) == 0x000000, "Member 'BP_StringTrap_C_IsTriggerActor::Actor' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_IsTriggerActor, Result) == 0x000008, "Member 'BP_StringTrap_C_IsTriggerActor::Result' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_IsTriggerActor, Character) == 0x000010, "Member 'BP_StringTrap_C_IsTriggerActor::Character' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_IsTriggerActor, K2Node_DynamicCast_AsBP_Killable_Character) == 0x000018, "Member 'BP_StringTrap_C_IsTriggerActor::K2Node_DynamicCast_AsBP_Killable_Character' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_IsTriggerActor, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_StringTrap_C_IsTriggerActor::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_IsTriggerActor, CallFunc_GetAffinity_Affinity) == 0x000021, "Member 'BP_StringTrap_C_IsTriggerActor::CallFunc_GetAffinity_Affinity' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_IsTriggerActor, CallFunc_Not_PreBool_ReturnValue) == 0x000022, "Member 'BP_StringTrap_C_IsTriggerActor::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_StringTrap_C_IsTriggerActor, CallFunc_BooleanOR_ReturnValue) == 0x000023, "Member 'BP_StringTrap_C_IsTriggerActor::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

}

