#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Velociralien_Uncommon

#include "Basic.hpp"

#include "BP_Velociralien_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Velociralien_Uncommon.BP_Velociralien_Uncommon_C
// 0x0000 (0x0B50 - 0x0B50)
class ABP_Velociralien_Uncommon_C final : public ABP_Velociralien_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Velociralien_Uncommon_C">();
	}
	static class ABP_Velociralien_Uncommon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Velociralien_Uncommon_C>();
	}
};
static_assert(alignof(ABP_Velociralien_Uncommon_C) == 0x000010, "Wrong alignment on ABP_Velociralien_Uncommon_C");
static_assert(sizeof(ABP_Velociralien_Uncommon_C) == 0x000B50, "Wrong size on ABP_Velociralien_Uncommon_C");

}

