#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_PlayerFear

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BPC_PlayerFear.BPC_PlayerFear_C.ComponentBeginOverlap
// 0x0108 (0x0108 - 0x0000)
struct BPC_PlayerFear_C_ComponentBeginOverlap final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BPC_PlayerFear_C_ComponentBeginOverlap) == 0x000008, "Wrong alignment on BPC_PlayerFear_C_ComponentBeginOverlap");
static_assert(sizeof(BPC_PlayerFear_C_ComponentBeginOverlap) == 0x000108, "Wrong size on BPC_PlayerFear_C_ComponentBeginOverlap");
static_assert(offsetof(BPC_PlayerFear_C_ComponentBeginOverlap, OverlappedComponent) == 0x000000, "Member 'BPC_PlayerFear_C_ComponentBeginOverlap::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ComponentBeginOverlap, OtherActor) == 0x000008, "Member 'BPC_PlayerFear_C_ComponentBeginOverlap::OtherActor' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ComponentBeginOverlap, OtherComp) == 0x000010, "Member 'BPC_PlayerFear_C_ComponentBeginOverlap::OtherComp' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ComponentBeginOverlap, OtherBodyIndex) == 0x000018, "Member 'BPC_PlayerFear_C_ComponentBeginOverlap::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ComponentBeginOverlap, bFromSweep) == 0x00001C, "Member 'BPC_PlayerFear_C_ComponentBeginOverlap::bFromSweep' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ComponentBeginOverlap, SweepResult) == 0x000020, "Member 'BPC_PlayerFear_C_ComponentBeginOverlap::SweepResult' has a wrong offset!");

// Function BPC_PlayerFear.BPC_PlayerFear_C.ComponentEndOverlap
// 0x0020 (0x0020 - 0x0000)
struct BPC_PlayerFear_C_ComponentEndOverlap final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_PlayerFear_C_ComponentEndOverlap) == 0x000008, "Wrong alignment on BPC_PlayerFear_C_ComponentEndOverlap");
static_assert(sizeof(BPC_PlayerFear_C_ComponentEndOverlap) == 0x000020, "Wrong size on BPC_PlayerFear_C_ComponentEndOverlap");
static_assert(offsetof(BPC_PlayerFear_C_ComponentEndOverlap, OverlappedComponent) == 0x000000, "Member 'BPC_PlayerFear_C_ComponentEndOverlap::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ComponentEndOverlap, OtherActor) == 0x000008, "Member 'BPC_PlayerFear_C_ComponentEndOverlap::OtherActor' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ComponentEndOverlap, OtherComp) == 0x000010, "Member 'BPC_PlayerFear_C_ComponentEndOverlap::OtherComp' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ComponentEndOverlap, OtherBodyIndex) == 0x000018, "Member 'BPC_PlayerFear_C_ComponentEndOverlap::OtherBodyIndex' has a wrong offset!");

// Function BPC_PlayerFear.BPC_PlayerFear_C.ExecuteUbergraph_BPC_PlayerFear
// 0x0540 (0x0540 - 0x0000)
struct BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_CustomEvent_OverlappedComponent_1;          // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_OtherActor_1;                   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_CustomEvent_OtherComp_1;                    // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_OtherBodyIndex_1;               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bFromSweep;                     // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_CustomEvent_SweepResult;                    // 0x0028(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	TArray<class UPrimitiveComponent*>            CallFunc_GetOverlappingComponents_OutOverlappingComponents; // 0x0110(0x0010)(ReferenceParm, ContainsInstancedReference)
	class USceneComponent*                        CallFunc_GetAttachParent_ReturnValue;              // 0x0120(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBPC_FearSource_C*                      K2Node_DynamicCast_AsBPC_Fear_Source;              // 0x0130(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_CustomEvent_OverlappedComponent;            // 0x0140(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_OtherActor;                     // 0x0148(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_CustomEvent_OtherComp;                      // 0x0150(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_OtherBodyIndex;                 // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        CallFunc_GetAttachParent_ReturnValue_1;            // 0x0160(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UBPC_FearSource_C*                      K2Node_DynamicCast_AsBPC_Fear_Source_1;            // 0x0168(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_171[0x3];                                      // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_179[0x3];                                      // 0x0179(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetActiveFear_Active;                     // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetActiveFear_FearPerSecond;              // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetActiveFear_MinFear;                    // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetActiveFear_MaxFear;                    // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x01B0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)> K2Node_CreateDelegate_OutputDelegate; // 0x0218(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_231[0x7];                                      // 0x0231(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue_1;                   // 0x0240(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_FClamp_ReturnValue_1;                     // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue_2;                   // 0x0260(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_UPPlayerCharacter_C*                K2Node_DynamicCast_AsBP_UPPlayer_Character;        // 0x0270(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_279[0x3];                                      // 0x0279(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)> K2Node_CreateDelegate_OutputDelegate_1; // 0x027C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28C[0x4];                                      // 0x028C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue_3;                   // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_2;               // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0299(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x029A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29B[0x5];                                      // 0x029B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x02A0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_AddComponentByClass_ReturnValue;          // 0x0300(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0308(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x030C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_30D[0x3];                                      // 0x030D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0310(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Enabled;                        // 0x0314(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0315(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_BoolBool_ReturnValue;            // 0x0316(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_317[0x9];                                      // 0x0317(0x0009)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_2;              // 0x0320(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0380(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_384[0x4];                                      // 0x0384(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPostProcessComponent*                  CallFunc_AddComponentByClass_ReturnValue_1;        // 0x0388(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_Array_Get_Item;                           // 0x0390(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue_4;                   // 0x0398(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue;                // 0x03A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x03A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A5[0x3];                                      // 0x03A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x03A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetGameTimeInSeconds_ReturnValue_1;       // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_1;      // 0x03B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_1;       // 0x03C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C1[0x7];                                      // 0x03C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_2;      // 0x03C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x03D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue_2;                     // 0x03D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x03E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue_1;       // 0x03E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3E2[0x6];                                      // 0x03E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_CustomEvent_MinFear;                        // 0x03E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       CallFunc_AddComponentByClass_ReturnValue_2;        // 0x03F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_2;       // 0x03F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F9[0x7];                                      // 0x03F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetGameTimeInSeconds_ReturnValue_2;       // 0x0400(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0408(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_409[0x7];                                      // 0x0409(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             Temp_struct_Variable;                              // 0x0410(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_SetSphereRadius_InSphereRadius_ImplicitCast; // 0x04F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4FC[0x4];                                      // 0x04FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0500(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x0508(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetFloatParameter_InFloat_ImplicitCast;   // 0x0510(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast;        // 0x0514(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_Value_ImplicitCast;                // 0x0518(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast;          // 0x0520(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_A_ImplicitCast;     // 0x0528(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_BlendWeight_ImplicitCast;       // 0x0530(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear) == 0x000010, "Wrong alignment on BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear");
static_assert(sizeof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear) == 0x000540, "Wrong size on BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, EntryPoint) == 0x000000, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::EntryPoint' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Not_PreBool_ReturnValue) == 0x000004, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_OverlappedComponent_1) == 0x000008, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_OtherActor_1) == 0x000010, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_OtherComp_1) == 0x000018, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_OtherBodyIndex_1) == 0x000020, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_bFromSweep) == 0x000024, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_SweepResult) == 0x000028, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetOverlappingComponents_OutOverlappingComponents) == 0x000110, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetOverlappingComponents_OutOverlappingComponents' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetAttachParent_ReturnValue) == 0x000120, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetAttachParent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Array_Length_ReturnValue) == 0x000128, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_DynamicCast_AsBPC_Fear_Source) == 0x000130, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_DynamicCast_AsBPC_Fear_Source' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_DynamicCast_bSuccess) == 0x000138, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_OverlappedComponent) == 0x000140, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_OtherActor) == 0x000148, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_OtherComp) == 0x000150, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_OtherBodyIndex) == 0x000158, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetAttachParent_ReturnValue_1) == 0x000160, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetAttachParent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_DynamicCast_AsBPC_Fear_Source_1) == 0x000168, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_DynamicCast_AsBPC_Fear_Source_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_DynamicCast_bSuccess_1) == 0x000170, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Array_AddUnique_ReturnValue) == 0x000174, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Array_RemoveItem_ReturnValue) == 0x000178, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_Event_DeltaSeconds) == 0x00017C, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetActiveFear_Active) == 0x000180, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetActiveFear_Active' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetActiveFear_FearPerSecond) == 0x000188, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetActiveFear_FearPerSecond' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetActiveFear_MinFear) == 0x000190, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetActiveFear_MinFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetActiveFear_MaxFear) == 0x000198, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetActiveFear_MaxFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x0001A0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Add_DoubleDouble_ReturnValue) == 0x0001A8, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_MakeTransform_ReturnValue) == 0x0001B0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_FClamp_ReturnValue) == 0x000210, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CreateDelegate_OutputDelegate) == 0x000218, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetOwner_ReturnValue) == 0x000228, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_HasAuthority_ReturnValue) == 0x000230, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000238, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetOwner_ReturnValue_1) == 0x000240, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetOwner_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000248, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_HasAuthority_ReturnValue_1) == 0x000250, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_FClamp_ReturnValue_1) == 0x000258, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_FClamp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetOwner_ReturnValue_2) == 0x000260, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetOwner_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_IsValid_ReturnValue) == 0x000268, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_DynamicCast_AsBP_UPPlayer_Character) == 0x000270, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_DynamicCast_AsBP_UPPlayer_Character' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_DynamicCast_bSuccess_2) == 0x000278, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CreateDelegate_OutputDelegate_1) == 0x00027C, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetOwner_ReturnValue_3) == 0x000290, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetOwner_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_HasAuthority_ReturnValue_2) == 0x000298, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_HasAuthority_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_IsValid_ReturnValue_1) == 0x000299, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_K2_AttachToComponent_ReturnValue) == 0x00029A, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_MakeTransform_ReturnValue_1) == 0x0002A0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_AddComponentByClass_ReturnValue) == 0x000300, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_AddComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, Temp_int_Loop_Counter_Variable) == 0x000308, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Less_IntInt_ReturnValue) == 0x00030C, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Add_IntInt_ReturnValue) == 0x000310, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_Enabled) == 0x000314, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_Enabled' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000315, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_NotEqual_BoolBool_ReturnValue) == 0x000316, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_NotEqual_BoolBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_MakeTransform_ReturnValue_2) == 0x000320, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_MakeTransform_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, Temp_int_Array_Index_Variable) == 0x000380, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_AddComponentByClass_ReturnValue_1) == 0x000388, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_AddComponentByClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Array_Get_Item) == 0x000390, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetOwner_ReturnValue_4) == 0x000398, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetOwner_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetFloatValue_ReturnValue) == 0x0003A0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetFloatValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_IsValid_ReturnValue_2) == 0x0003A4, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetGameTimeInSeconds_ReturnValue) == 0x0003A8, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetGameTimeInSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetGameTimeInSeconds_ReturnValue_1) == 0x0003B0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetGameTimeInSeconds_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Subtract_DoubleDouble_ReturnValue_1) == 0x0003B8, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Subtract_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Greater_DoubleDouble_ReturnValue_1) == 0x0003C0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Greater_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Subtract_DoubleDouble_ReturnValue_2) == 0x0003C8, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Subtract_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x0003D0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_FClamp_ReturnValue_2) == 0x0003D8, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_FClamp_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x0003E0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_K2_AttachToComponent_ReturnValue_1) == 0x0003E1, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_K2_AttachToComponent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_CustomEvent_MinFear) == 0x0003E8, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_CustomEvent_MinFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_AddComponentByClass_ReturnValue_2) == 0x0003F0, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_AddComponentByClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Greater_DoubleDouble_ReturnValue_2) == 0x0003F8, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Greater_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetGameTimeInSeconds_ReturnValue_2) == 0x000400, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetGameTimeInSeconds_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_BooleanAND_ReturnValue) == 0x000408, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, Temp_struct_Variable) == 0x000410, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_SetSphereRadius_InSphereRadius_ImplicitCast) == 0x0004F8, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_SetSphereRadius_InSphereRadius_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000500, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Multiply_DoubleDouble_B_ImplicitCast) == 0x000508, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Multiply_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_SetFloatParameter_InFloat_ImplicitCast) == 0x000510, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_SetFloatParameter_InFloat_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_GetFloatValue_InTime_ImplicitCast) == 0x000514, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_GetFloatValue_InTime_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_FClamp_Value_ImplicitCast) == 0x000518, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_FClamp_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Add_DoubleDouble_A_ImplicitCast) == 0x000520, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Add_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, CallFunc_Subtract_DoubleDouble_A_ImplicitCast) == 0x000528, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::CallFunc_Subtract_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear, K2Node_VariableSet_BlendWeight_ImplicitCast) == 0x000530, "Member 'BPC_PlayerFear_C_ExecuteUbergraph_BPC_PlayerFear::K2Node_VariableSet_BlendWeight_ImplicitCast' has a wrong offset!");

// Function BPC_PlayerFear.BPC_PlayerFear_C.GetActiveFear
// 0x00A0 (0x00A0 - 0x0000)
struct BPC_PlayerFear_C_GetActiveFear final
{
public:
	bool                                          Active;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        FearPerSecond;                                     // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MinFear;                                           // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MaxFear;                                           // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        _MinFear;                                          // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        _MaxFear;                                          // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        _FearPerSecond;                                    // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_1;       // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x2];                                       // 0x003A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBPC_FearSource_C*                      CallFunc_Array_Get_Item;                           // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Set_Contains_ReturnValue;                 // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x005E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInSight_Result;                         // 0x005F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetFearSettings_IsActive;                 // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetFearSettings_FearPerSecond;            // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetFearSettings_MaxFear;                  // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetFearSettings_CheckSight;               // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetFearSettings_JumpFear;                 // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_2;       // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x008A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue_1;          // 0x008B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_PlayerFear_C_GetActiveFear) == 0x000008, "Wrong alignment on BPC_PlayerFear_C_GetActiveFear");
static_assert(sizeof(BPC_PlayerFear_C_GetActiveFear) == 0x0000A0, "Wrong size on BPC_PlayerFear_C_GetActiveFear");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, Active) == 0x000000, "Member 'BPC_PlayerFear_C_GetActiveFear::Active' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, FearPerSecond) == 0x000008, "Member 'BPC_PlayerFear_C_GetActiveFear::FearPerSecond' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, MinFear) == 0x000010, "Member 'BPC_PlayerFear_C_GetActiveFear::MinFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, MaxFear) == 0x000018, "Member 'BPC_PlayerFear_C_GetActiveFear::MaxFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, _MinFear) == 0x000020, "Member 'BPC_PlayerFear_C_GetActiveFear::_MinFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, _MaxFear) == 0x000028, "Member 'BPC_PlayerFear_C_GetActiveFear::_MaxFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, _FearPerSecond) == 0x000030, "Member 'BPC_PlayerFear_C_GetActiveFear::_FearPerSecond' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000038, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Greater_DoubleDouble_ReturnValue_1) == 0x000039, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Greater_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, Temp_int_Array_Index_Variable) == 0x00003C, "Member 'BPC_PlayerFear_C_GetActiveFear::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_BooleanOR_ReturnValue) == 0x000040, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, Temp_int_Loop_Counter_Variable) == 0x000044, "Member 'BPC_PlayerFear_C_GetActiveFear::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Add_IntInt_ReturnValue) == 0x000048, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Array_Get_Item) == 0x000050, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Less_IntInt_ReturnValue) == 0x00005C, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Set_Contains_ReturnValue) == 0x00005D, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Set_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Not_PreBool_ReturnValue) == 0x00005E, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_IsInSight_Result) == 0x00005F, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_IsInSight_Result' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_GetFearSettings_IsActive) == 0x000060, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_GetFearSettings_IsActive' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_GetFearSettings_FearPerSecond) == 0x000068, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_GetFearSettings_FearPerSecond' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_GetFearSettings_MaxFear) == 0x000070, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_GetFearSettings_MaxFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_GetFearSettings_CheckSight) == 0x000078, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_GetFearSettings_CheckSight' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_GetFearSettings_JumpFear) == 0x000080, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_GetFearSettings_JumpFear' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000088, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Greater_DoubleDouble_ReturnValue_2) == 0x000089, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Greater_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_BooleanAND_ReturnValue) == 0x00008A, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Less_DoubleDouble_ReturnValue_1) == 0x00008B, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Less_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000090, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_GetActiveFear, CallFunc_IsValid_ReturnValue) == 0x000098, "Member 'BPC_PlayerFear_C_GetActiveFear::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BPC_PlayerFear.BPC_PlayerFear_C.InstantFear
// 0x0008 (0x0008 - 0x0000)
struct BPC_PlayerFear_C_InstantFear final
{
public:
	double                                        MinFear;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_PlayerFear_C_InstantFear) == 0x000008, "Wrong alignment on BPC_PlayerFear_C_InstantFear");
static_assert(sizeof(BPC_PlayerFear_C_InstantFear) == 0x000008, "Wrong size on BPC_PlayerFear_C_InstantFear");
static_assert(offsetof(BPC_PlayerFear_C_InstantFear, MinFear) == 0x000000, "Member 'BPC_PlayerFear_C_InstantFear::MinFear' has a wrong offset!");

// Function BPC_PlayerFear.BPC_PlayerFear_C.IsInSight
// 0x0180 (0x0180 - 0x0000)
struct BPC_PlayerFear_C_IsInSight final
{
public:
	class UBPC_FearSource_C*                      FearSource;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0030(0x0010)(ConstParm, ReferenceParm)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x0040(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x0058(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0070(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15A[0x6];                                      // 0x015A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInFrustrum_Result;                      // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_PlayerFear_C_IsInSight) == 0x000008, "Wrong alignment on BPC_PlayerFear_C_IsInSight");
static_assert(sizeof(BPC_PlayerFear_C_IsInSight) == 0x000180, "Wrong size on BPC_PlayerFear_C_IsInSight");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, FearSource) == 0x000000, "Member 'BPC_PlayerFear_C_IsInSight::FearSource' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, Result) == 0x000008, "Member 'BPC_PlayerFear_C_IsInSight::Result' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_GetOwner_ReturnValue) == 0x000010, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000018, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, K2Node_MakeArray_Array) == 0x000030, "Member 'BPC_PlayerFear_C_IsInSight::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x000040, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x000058, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_LineTraceSingle_OutHit) == 0x000070, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_LineTraceSingle_ReturnValue) == 0x000158, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_Not_PreBool_ReturnValue) == 0x000159, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000160, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000168, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_IsInFrustrum_Result) == 0x000170, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_IsInFrustrum_Result' has a wrong offset!");
static_assert(offsetof(BPC_PlayerFear_C_IsInSight, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000178, "Member 'BPC_PlayerFear_C_IsInSight::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function BPC_PlayerFear.BPC_PlayerFear_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BPC_PlayerFear_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_PlayerFear_C_ReceiveTick) == 0x000004, "Wrong alignment on BPC_PlayerFear_C_ReceiveTick");
static_assert(sizeof(BPC_PlayerFear_C_ReceiveTick) == 0x000004, "Wrong size on BPC_PlayerFear_C_ReceiveTick");
static_assert(offsetof(BPC_PlayerFear_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BPC_PlayerFear_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BPC_PlayerFear.BPC_PlayerFear_C.SetFearSoundEnabled
// 0x0001 (0x0001 - 0x0000)
struct BPC_PlayerFear_C_SetFearSoundEnabled final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_PlayerFear_C_SetFearSoundEnabled) == 0x000001, "Wrong alignment on BPC_PlayerFear_C_SetFearSoundEnabled");
static_assert(sizeof(BPC_PlayerFear_C_SetFearSoundEnabled) == 0x000001, "Wrong size on BPC_PlayerFear_C_SetFearSoundEnabled");
static_assert(offsetof(BPC_PlayerFear_C_SetFearSoundEnabled, Enabled) == 0x000000, "Member 'BPC_PlayerFear_C_SetFearSoundEnabled::Enabled' has a wrong offset!");

}

