#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_ParentEnemy

#include "Basic.hpp"

#include "BPC_ParentEnemy_classes.hpp"
#include "BPC_ParentEnemy_parameters.hpp"


namespace SDK
{

// Function BPC_ParentEnemy.BPC_ParentEnemy_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPC_ParentEnemy_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ParentEnemy_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_ParentEnemy.BPC_ParentEnemy_C.ReceivePossess
// (Event, Protected, BlueprintEvent)
// Parameters:
// class APawn*                            PossessedPawn                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABPC_ParentEnemy_C::ReceivePossess(class APawn* PossessedPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ParentEnemy_C", "ReceivePossess");

	Params::BPC_ParentEnemy_C_ReceivePossess Parms{};

	Parms.PossessedPawn = PossessedPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ParentEnemy.BPC_ParentEnemy_C.ExecuteUbergraph_BPC_ParentEnemy
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPC_ParentEnemy_C::ExecuteUbergraph_BPC_ParentEnemy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ParentEnemy_C", "ExecuteUbergraph_BPC_ParentEnemy");

	Params::BPC_ParentEnemy_C_ExecuteUbergraph_BPC_ParentEnemy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

