#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_Parasite

#include "Basic.hpp"

#include "BPC_ParentEnemy_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_Parasite.BPC_Parasite_C
// 0x0000 (0x03E8 - 0x03E8)
class ABPC_Parasite_C final : public ABPC_ParentEnemy_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPC_Parasite_C">();
	}
	static class ABPC_Parasite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPC_Parasite_C>();
	}
};
static_assert(alignof(ABPC_Parasite_C) == 0x000008, "Wrong alignment on ABPC_Parasite_C");
static_assert(sizeof(ABPC_Parasite_C) == 0x0003E8, "Wrong size on ABPC_Parasite_C");

}

