#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Killer

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_Killer.BPI_Killer_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_Killer_C final
{
public:
	void HasHarmed__All_(TScriptInterface<class IBPI_Killable_C> HarmedActor);
	void HasHarmed__Server_(TScriptInterface<class IBPI_Killable_C> HarmedActor);
	void HasKilled__All_(TScriptInterface<class IBPI_Killable_C> KilledActor);
	void HasKilled__Server_(TScriptInterface<class IBPI_Killable_C> KilledActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_Killer_C">();
	}
	static class IBPI_Killer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Killer_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_Killer_C) == 0x000001, "Wrong alignment on IBPI_Killer_C");
static_assert(sizeof(IBPI_Killer_C) == 0x000001, "Wrong size on IBPI_Killer_C");

}

