#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTS_SurvivorInteriorState

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_InteriorSurvivorState_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTS_SurvivorInteriorState.BTS_SurvivorInteriorState_C
// 0x0010 (0x00A8 - 0x0098)
class UBTS_SurvivorInteriorState_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	E_InteriorSurvivorState                       State;                                             // 0x00A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BTS_SurvivorInteriorState(int32 EntryPoint);
	void ReceiveActivationAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTS_SurvivorInteriorState_C">();
	}
	static class UBTS_SurvivorInteriorState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTS_SurvivorInteriorState_C>();
	}
};
static_assert(alignof(UBTS_SurvivorInteriorState_C) == 0x000008, "Wrong alignment on UBTS_SurvivorInteriorState_C");
static_assert(sizeof(UBTS_SurvivorInteriorState_C) == 0x0000A8, "Wrong size on UBTS_SurvivorInteriorState_C");
static_assert(offsetof(UBTS_SurvivorInteriorState_C, UberGraphFrame) == 0x000098, "Member 'UBTS_SurvivorInteriorState_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBTS_SurvivorInteriorState_C, State) == 0x0000A0, "Member 'UBTS_SurvivorInteriorState_C::State' has a wrong offset!");

}

