#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Notification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Notification.W_Notification_C
// 0x0010 (0x02D0 - 0x02C0)
class UW_Notification_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             NotificationText;                                  // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_Notification(int32 EntryPoint);
	void InitNotification(const class FString& Notification, double Duration);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_Notification_C">();
	}
	static class UW_Notification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Notification_C>();
	}
};
static_assert(alignof(UW_Notification_C) == 0x000008, "Wrong alignment on UW_Notification_C");
static_assert(sizeof(UW_Notification_C) == 0x0002D0, "Wrong size on UW_Notification_C");
static_assert(offsetof(UW_Notification_C, UberGraphFrame) == 0x0002C0, "Member 'UW_Notification_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_Notification_C, NotificationText) == 0x0002C8, "Member 'UW_Notification_C::NotificationText' has a wrong offset!");

}

